repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0  # Vous pouvez vérifier la dernière version sur GitHub
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml

  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0  # Vous pouvez vérifier la dernière version sur GitHub
    hooks:
      - id: flake8
        additional_dependencies: [pycodestyle]
